import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import Sidebar from "./sidebar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
          antialiased flex flex-col bg-gray-800 min-h-screen`}
      >
        <Sidebar />
        <main className="flex w-full">
          <div className="pl-64 pt-5 w-full flex flex-col gap-5">
            <Header />
            <div className="p-6 bg-gray-900 text-white shadow-md rounded-lg">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
